[21:52:09|27-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2942
SyntaxError: positional argument follows keyword argument

[13:32:04|28-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2514
SyntaxError: positional argument follows keyword argument

